version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: evolveedu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./evolveedu-ai/backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/evolveedu

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./evolveedu-ai/frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000/api

volumes:
  postgres_data:
