# Generated by Django 5.2.7 on 2025-11-01 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("strength", "Learning Strength"),
                            ("weakness", "Area for Improvement"),
                            ("pattern", "Learning Pattern"),
                            ("recommendation", "Study Recommendation"),
                            ("achievement", "Learning Achievement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("subject_area", models.CharField(blank=True, max_length=100)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("supporting_data", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("is_actionable", models.BooleanField(default=True)),
                ("suggested_actions", models.JSONField(blank=True, default=list)),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("user_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Plan"),
                            ("weekly", "Weekly Plan"),
                            ("exam_prep", "Exam Preparation"),
                            ("topic_mastery", "Topic Mastery"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("topics", models.JSONField(default=list)),
                ("duration_days", models.IntegerField(default=7)),
                ("daily_study_time", models.IntegerField(default=60)),
                ("study_schedule", models.JSONField(default=dict)),
                ("milestones", models.JSONField(default=list)),
                ("resources", models.JSONField(default=list)),
                ("current_day", models.IntegerField(default=1)),
                ("completion_percentage", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("total_tasks", models.IntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("adherence_score", models.IntegerField(default=0)),
                ("effectiveness_rating", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TutorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat Session"),
                            ("problem_solving", "Problem Solving"),
                            ("concept_explanation", "Concept Explanation"),
                            ("homework_help", "Homework Help"),
                            ("exam_prep", "Exam Preparation"),
                        ],
                        default="chat",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(default=0)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("learning_objectives", models.JSONField(blank=True, default=list)),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                ("user_feedback", models.TextField(blank=True)),
                ("session_summary", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TutorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("session_rating", "Session Rating"),
                            ("feature_request", "Feature Request"),
                            ("bug_report", "Bug Report"),
                            ("general", "General Feedback"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("content_quality", models.IntegerField(blank=True, null=True)),
                ("response_speed", models.IntegerField(blank=True, null=True)),
                ("helpfulness", models.IntegerField(blank=True, null=True)),
                ("user_experience", models.IntegerField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("admin_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tutor.tutorsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemSolvingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_statement", models.TextField()),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("math", "Mathematics"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("programming", "Programming"),
                            ("logic", "Logic/Reasoning"),
                            ("general", "General Problem"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "problem_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="problem_images/"
                    ),
                ),
                (
                    "problem_file",
                    models.FileField(blank=True, null=True, upload_to="problem_files/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("analyzing", "Analyzing Problem"),
                            ("solving", "Working on Solution"),
                            ("reviewing", "Reviewing Solution"),
                            ("completed", "Completed"),
                        ],
                        default="analyzing",
                        max_length=20,
                    ),
                ),
                ("solution_steps", models.JSONField(blank=True, default=list)),
                ("final_answer", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("key_concepts", models.JSONField(blank=True, default=list)),
                ("similar_problems", models.JSONField(blank=True, default=list)),
                ("learning_resources", models.JSONField(blank=True, default=list)),
                ("hints_used", models.IntegerField(default=0)),
                ("attempts_made", models.IntegerField(default=0)),
                ("time_spent_minutes", models.IntegerField(default=0)),
                ("understanding_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_session",
                        to="tutor.tutorsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConceptExplanation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concept_name", models.CharField(max_length=200)),
                ("subject_area", models.CharField(max_length=100)),
                ("explanation_request", models.TextField()),
                ("explanation", models.TextField()),
                ("examples", models.JSONField(blank=True, default=list)),
                ("analogies", models.JSONField(blank=True, default=list)),
                ("visual_aids", models.JSONField(blank=True, default=list)),
                ("prerequisites", models.JSONField(blank=True, default=list)),
                ("related_concepts", models.JSONField(blank=True, default=list)),
                ("practice_questions", models.JSONField(blank=True, default=list)),
                ("explanation_rating", models.IntegerField(blank=True, null=True)),
                ("clarity_score", models.IntegerField(blank=True, null=True)),
                ("follow_up_questions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_explanations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_explanation",
                        to="tutor.tutorsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("tutor", "AI Tutor Response"),
                            ("system", "System Message"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("intent", models.CharField(blank=True, max_length=50)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("topic_tags", models.JSONField(blank=True, default=list)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("needs_followup", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tutor.tutorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
