# Generated by Django 5.2.7 on 2025-11-01 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("average_salary_min", models.IntegerField(default=0)),
                ("average_salary_max", models.IntegerField(default=0)),
                ("job_growth_rate", models.FloatField(default=0.0)),
                ("total_estimated_months", models.IntegerField(default=12)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🎯", max_length=50)),
            ],
            options={
                "verbose_name_plural": "Skill Categories",
            },
        ),
        migrations.CreateModel(
            name="PersonalizedRoadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("current_skill_level", models.JSONField(default=dict)),
                ("start_date", models.DateField()),
                ("target_completion_date", models.DateField()),
                ("estimated_hours_per_week", models.IntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("overall_progress_percentage", models.IntegerField(default=0)),
                ("completed_milestones", models.JSONField(default=list)),
                ("personalized_recommendations", models.JSONField(default=list)),
                ("weekly_goals", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_career_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="roadmaps.careerpath",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("estimated_hours", models.IntegerField(default=10)),
                ("market_demand", models.IntegerField(default=50)),
                ("avg_salary_impact", models.IntegerField(default=0)),
                ("learning_resources", models.JSONField(blank=True, default=list)),
                ("practice_projects", models.JSONField(blank=True, default=list)),
                ("is_trending", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="unlocks", to="roadmaps.skill"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="roadmaps.skillcategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "category")},
            },
        ),
        migrations.CreateModel(
            name="RoadmapMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("learning_resources", models.JSONField(default=list)),
                ("practice_tasks", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("estimated_hours", models.IntegerField(default=5)),
                ("actual_hours_spent", models.IntegerField(default=0)),
                ("planned_start_date", models.DateField(blank=True, null=True)),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("completion_criteria", models.JSONField(default=list)),
                ("assessment_score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="roadmaps.personalizedroadmap",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="roadmaps.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="personalizedroadmap",
            name="target_skills",
            field=models.ManyToManyField(
                related_name="targeted_by_roadmaps", to="roadmaps.skill"
            ),
        ),
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("video", "Video"),
                            ("course", "Online Course"),
                            ("book", "Book"),
                            ("tutorial", "Tutorial"),
                            ("documentation", "Documentation"),
                            ("project", "Project"),
                            ("practice", "Practice Exercise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("estimated_duration", models.CharField(blank=True, max_length=50)),
                ("cost", models.CharField(default="free", max_length=20)),
                ("rating", models.FloatField(default=0.0)),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("content_quality_score", models.IntegerField(default=80)),
                ("relevance_score", models.IntegerField(default=80)),
                ("is_recommended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="resources", to="roadmaps.skill"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="careerpath",
            name="recommended_skills",
            field=models.ManyToManyField(
                blank=True, related_name="recommended_for_paths", to="roadmaps.skill"
            ),
        ),
        migrations.AddField(
            model_name="careerpath",
            name="required_skills",
            field=models.ManyToManyField(
                related_name="required_for_paths", to="roadmaps.skill"
            ),
        ),
        migrations.AddField(
            model_name="careerpath",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_paths",
                to="roadmaps.skillcategory",
            ),
        ),
        migrations.CreateModel(
            name="SkillAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.IntegerField()),
                ("projects_completed", models.JSONField(default=list)),
                ("certifications", models.JSONField(default=list)),
                ("years_of_experience", models.FloatField(default=0.0)),
                (
                    "assessment_method",
                    models.CharField(default="self_assessment", max_length=50),
                ),
                ("assessment_date", models.DateTimeField(auto_now_add=True)),
                ("skill_gaps", models.JSONField(default=list)),
                ("improvement_suggestions", models.JSONField(default=list)),
                ("next_learning_steps", models.JSONField(default=list)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="roadmaps.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "skill")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("bookmarked", "Bookmarked"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("time_spent_minutes", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("review", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(blank=True, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="roadmaps.learningresource",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmaps.personalizedroadmap",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "resource")},
            },
        ),
    ]
